/**
 * Migration script — imports all books from the original hobbyjapan-clone
 * into your Sanity dataset.
 *
 * Usage:
 *   1. Copy .env.local.example to .env.local and fill in your values
 *   2. npm run migrate
 */

import { createClient } from '@sanity/client'
import { config } from 'dotenv'
import { fileURLToPath } from 'url'
import { dirname, resolve } from 'path'
import { readFileSync } from 'fs'

const __dirname = dirname(fileURLToPath(import.meta.url))
config({ path: resolve(__dirname, '../.env.local') })

const client = createClient({
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID,
  dataset: process.env.NEXT_PUBLIC_SANITY_DATASET || 'production',
  token: process.env.SANITY_API_TOKEN,
  apiVersion: '2024-01-01',
  useCdn: false,
})

if (!process.env.NEXT_PUBLIC_SANITY_PROJECT_ID || !process.env.SANITY_API_TOKEN) {
  console.error('❌  Missing env vars. Copy .env.local.example to .env.local and fill in values.')
  process.exit(1)
}

const books = [
  {
    slug: 'war-in-the-pocket',
    series: 'HJ MECHANICS',
    title: 'Mobile Suit Gundam 0080: War in the Pocket',
    subtitle: 'A complete deep-dive into the iconic mobile suits',
    isNew: true,
    releaseDate: '2026/3/16',
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_755d0f91992f465bb41784c78474f2b4~mv2.jpg/v1/fill/w_308,h_392,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B0GS5PJ23J/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_480873736bc1444ba193876904c1cdd7.pdf',
    description: `This special volume of HJ Mechanics shines a spotlight on the beloved 1989 OVA series—a story set against the backdrop of colonial Christmas, told not through the eyes of heroes, but through soldiers and the machines they piloted. Featuring the full roster of mobile suits that defined the series—from the RX-78NT-1 Gundam "Alex" to the fearsome MS-18E Kämpfer, the late-war Zaku II FZ, and the Cyclops Team's amphibious units—this issue brings together some of Japan's finest builders to take each kit to the next level through meticulous modification, dynamic dioramas, and deep technical commentary.`,
  },
  {
    slug: 'ibo2',
    series: 'GUNDAM FORWARD',
    title: 'Mobile Suit Gundam: Iron-Blooded Orphans 10th Anniversary',
    subtitle: 'The Iron Flower That Never Withers',
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_728e7c4be5eb4c0a8584da084e749ac1~mv2.jpg/v1/fill/w_305,h_420,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B0DJ88NL9B/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_b100f3c346ec435b823b002f174e80d6.pdf',
    description: `This issue marks a decade since the premiere of Mobile Suit Gundam: Iron-Blooded Orphans by showcasing pro-tier builds and world-building insights. The primary highlight is a detailed feature on the all-new MG Gundam Barbatos Lupus, accompanied by scratch builds and modifications from the Urdr-Hunt and MSV series. Additionally, the volume includes an exclusive look at the film Mobile Suit Gundam: Hathaway — The Sorcery of the Nymph Circe, featuring trailer stills and comments from the main cast.`,
  },
  {
    slug: 'ggundam',
    series: 'GUNDAM FORWARD',
    title: 'Mobile Fighter G Gundam',
    subtitle: 'Master-Level Gunpla Techniques: The Definitive Guide to Mobile Fighter Mecha',
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_d01313eccd314059aebc50887c9c7d0b~mv2.jpg/v1/fill/w_305,h_432,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B0G67B72L1/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_22411a5c1012453ebfa289f589fe7dae.pdf',
    description: `Unleash the supreme power of the Gundam Fight with this in-depth special feature! This volume is essential for serious modelers, providing a comprehensive guide to advanced Gunpla customization and finishing techniques, all centered on the highly dynamic Mobile Fighters of Mobile Fighter G Gundam.`,
  },
  {
    slug: 'gf-gquuuuuux',
    series: 'GUNDAM FORWARD',
    title: 'Mobile Suit Gundam GQuuuuuuX',
    subtitle: "Feel the 'Kira-Kira'! in the universe of Gundam GQuuuuuuX!",
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_35947644ecd3461f8b71da143997ccd2~mv2.jpg/v1/fill/w_305,h_432,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B0FQB585SG/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_c1d1b99583c847eaa93bb6e708cc45d3.pdf',
    description: `This issue features an in-depth look at Mobile Suit Gundam GQuuuuuuX, the newest installment in the Gundam series, brought to life through a collaboration between Studio Khara and Sunrise. We've packed this issue with everything from a comprehensive introduction to the series to the latest Gunpla news and amazing Gunpla build examples.`,
  },
  {
    slug: 'seeddestiny',
    series: 'GUNDAM FORWARD',
    title: 'Once Again! Mobile Suit Gundam SEED DESTINY',
    subtitle: 'SEED Destiny kit updated to the latest standards!',
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_5d00d2f90da14ccd9efe9fd322e0901e~mv2.jpg/v1/fill/w_305,h_431,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B0FHH1F8RQ/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_9f403bd59f9243fabb67d2a660684fb3.pdf',
    description: `This issue of Gundam Forward puts the spotlight on Mobile Suit Gundam SEED Destiny, celebrating its renewed popularity alongside the recent Mobile Suit Gundam SEED FREEDOM film and ongoing Gunpla releases.`,
  },
  {
    slug: 'gunpla-wt-textbook',
    series: 'TECHNIQUE GUIDE',
    title: 'Gunpla Weathering Textbook',
    subtitle: 'All About Gunpla Weathering!',
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_c5455b7747744f59b863d40a858416a4~mv2.jpg/v1/fill/w_305,h_431,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B0F9Y7T9CV/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_6c4c9edf74ec4dd1a5e854171fbd87ad.pdf',
    description: `Want to make your Gunpla look awesome? Keen to create your very own realistic, battle-scarred Gunpla that looks like it's been through the thick of it? Then look no further – weathering is the name of the game! This book is your essential guide to Gunpla-specific weathering. We'll deep dive into the latest techniques, materials, and inspiring ideas for every scenario – from quick tips to hardcore methods. It's packed with everything you need right now!`,
  },
  {
    slug: 'gf16',
    series: 'GUNDAM FORWARD',
    title: "Thanks to Gundam's 45th Anniversary – Here's to 45 Years of Gunpla",
    subtitle: 'Universal Century origins, reimagined!',
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_1c064fbaf60c46ec8640917879f36cd8~mv2.jpg/v1/fill/w_305,h_431,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B0F3WXQB86/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_c0a1f65cfddf436aae276e2ccc01c96e.pdf',
    description: `Celebrate 45 years of Gundam and the upcoming 45th anniversary of Gunpla with this special issue of Gundam Forward! Dive deep into the world of the original Mobile Suit Gundam with a spotlight on the stunning RG RX-78-2 Gundam Ver. 2.0. Discover breathtaking professional model builds of classic Gunpla from the series, presented alongside nostalgic diorama photography that brings iconic anime moments to life.`,
  },
  {
    slug: 'gf-f90-vol2',
    series: 'GUNDAM FORWARD',
    title: 'Mobile Suit Gundam F90 – F90 A to Z Project Part 2',
    subtitle: "Here's the second installment of our \"F90 A to Z PROJECT\" special!",
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_27446fbec47c48f1b78ca670f948094f~mv2.jpg/v1/fill/w_305,h_432,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B0DW8KH49Q/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_c3026f157a4e44d3b85c16953e55f916.pdf',
    description: `This issue doubles down on Mobile Suit Gundam F90, following up on the last issue's coverage! We're showcasing all the mission packs released so far, and the long-awaited MG F90III Cluster Gundam, which finally arrives six years after the "F90 A to Z PROJECT" first launched.`,
  },
  {
    slug: 'kota-scale-model-archive-book',
    series: 'SCALE MODEL',
    title: 'kota scale model archive book',
    subtitle: 'Enjoy building motorcycle models with a touch of ingenuity!',
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_0695b72c38b24e67ae1aa9f51bc6ac62~mv2.jpg/v1/fill/w_305,h_431,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B0DPZ5D5F9/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_352b2be668f94ebaba7af8eafa3d345a.pdf',
    description: `From his wildly popular social media channels to his upcoming book, kota scale model continues to push the boundaries of motorcycle modeling. With millions of followers hanging on his every post, kota is now sharing his secrets in his first-ever book. Inside, you'll find stunning custom builds, expert tips, and exclusive insights into the mind of a modeling maestro.`,
  },
  {
    slug: 'ten-essntial-gunpla-techniques2',
    series: 'TECHNIQUE GUIDE',
    title: 'Ten Essential Techniques to Achieve Absolute Mastery of Gunpla: ENTRY GRADE Strike Gundam Edition',
    subtitle: 'The most user-friendly Gunpla guide book is back!',
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_cd59caa5c1e14a6bb1b1d0999703cbfe~mv2.jpg/v1/fill/w_305,h_431,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B0DMRWS9TZ/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_6744cea099e944a0b62a996b69dc82e1.pdf',
    description: `The previous book, "Ten Essential Techniques to Achieve Absolute Mastery of Gunpla," was well-received by those new to Gunpla building because it focused on the easy but intricate ENTRY GRADE RX-78-2 Gundam. This time, we focus on the ENTRY GRADE Strike Gundam, the latest cutting-edge model of the ENTRY GRADE series! Master the basic techniques with this model and conquer any Gunpla!`,
  },
  {
    slug: 'gf14',
    series: 'GUNDAM FORWARD',
    title: 'Mobile Suit Gundam F90 – F90 A to Z Project',
    subtitle: 'Explore "F90 A to Z PROJECT"!',
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_4e159d7cc636463cabcf08961f0c7096~mv2.jpg/v1/fill/w_305,h_431,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B0DJGH52RV/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_ee928848fe0c41fda6465edf09e61891.pdf',
    description: `In this issue, we explore the development of the Gundam F90. With a focus on returning Mobile Suits to their original concept as versatile humanoid weapons, SNRI developed the F90. The design of the F90 featured a standardized main body with interchangeable mission packs. This issue highlights some of the lesser known packs.`,
  },
  {
    slug: 'hj-mechanics-gundam-zz',
    series: 'HJ MECHANICS',
    title: 'Mobile Suit Gundam ZZ',
    subtitle: 'Mobile Suit Technologies in U.C. 0088',
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_d83ba4a51846470d87316aa152db150b~mv2.jpg/v1/fill/w_307,h_392,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B0DGKR1WMN/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_ea80144fa9614ee2bb109e03289c9fed.pdf',
    description: `This issue features the Gundam team battling against various Neo Zeon mobile suits. Mobile Suit Gundam ZZ, which premiered on television in 1986, is a continuation of Mobile Suit Z Gundam. It plays a key role in connecting Z Gundam, Mobile Suit Gundam: Char's Counterattack, and Mobile Suit Gundam Unicorn.`,
  },
  {
    slug: 'hjmechanics18',
    series: 'HJ MECHANICS',
    title: "The Earth Federation Forces' Operation V",
    subtitle: "An in-depth look at the Earth Federation's Project V",
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_7216c8e4552f40a5bc51c1ec2b87a66d~mv2.jpg/v1/fill/w_307,h_392,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B0DCBKJD2S/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_dbffd9d5dc4044fdb6f7dcf73f3767d4.pdf',
    description: `In this issue, we explore the detailed historical background of Operation V and showcase the various Federation mobile suits developed as a result. This book highlights nearly all the pivotal mobile suits of the One Year War, allowing you to relive the famous battles of that era.`,
  },
  {
    slug: 'gunpla-easy-custom-guide2',
    series: 'TECHNIQUE GUIDE',
    title: 'Gunpla Easy Custom Guide 2: Casual Guide to Leveling Up Your Skills',
    subtitle: 'Welcome back to the World of Easy Modeling!',
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_740217bb149f4d9e91a3b5ec3a8cfb12~mv2.jpg/v1/fill/w_305,h_432,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B0D8VRPGGQ/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_1013b5f32d434ae9a8dbd65202bd1ee2.pdf',
    description: `Rider Joe, the popular author of "Gunpla Easy Custom Guide for Beginners to Intermediate," is back! Rider Joe, a dad-modeler who crafts his creations in his shared living room (with family and feline companions!), once again guides you through his easy and effective Gunpla building and painting techniques.`,
  },
  {
    slug: 'seira-masuo-s-wgpninuc',
    series: 'MODELER GUIDE',
    title: "Seira-Masuo's Whimsical Gunpla Production Notes in the Universal Century",
    subtitle: 'A Comprehensive Guide to the Unique Modeling Techniques of SEIRA-MASUO "Master of Details"',
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_f53ab74dafa2491199e73ab73b625299~mv2.jpg/v1/fill/w_305,h_432,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B0D41PQ37Q/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_c260cb83d2f04fd9a2f7e6e668f53d74.pdf',
    description: `Enter the world of Seira Masuo's distinctive modeling techniques, known as "Masuo Detailing," in this in-depth guide that breaks down each element for a thorough understanding. Building on the foundation laid in the previous installment, this sequel focuses on practical applications, using Gundam models from the Universal Century franchise as canvases for original customization.`,
  },
  {
    slug: 'gfvol13',
    series: 'GUNDAM FORWARD',
    title: 'Mobile Suit Gundam SEED – The Descending Sword',
    subtitle: 'Revisit the world of the original Gundam SEED series!',
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_544ea97bf86841f1b04d595ae27e944c~mv2.jpg/v1/fill/w_305,h_432,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B0CYDJVYJ9/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_3295ad586b824e39beaa0f03bf41ba41.pdf',
    description: `This issue of Gundam Forward covers Mobile Suit Gundam SEED again. This issue dives deeper than ever before, featuring iconic Mobile Suits like the Freedom and Justice Gundams, the later GAT-X series, and hidden gems from the SEED MSV spin-off.`,
  },
  {
    slug: 'seira-masuo-gunpla-notes',
    series: 'MODELER GUIDE',
    title: "Seira-Masuo's Whimsical Gunpla Production Notes",
    subtitle: "Monthly Hobby Japan's Popular Modeler Publishes Gunpla Technique Book!",
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_6df81a3e6c7e4e92a34b08f25e60b072~mv2.jpg/v1/fill/w_305,h_431,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B0CV58B14H/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_7c82c37a45064fc4ba51f58bf2671b64.pdf',
    description: `With this book, you will get an inside look at how Masuo creates his trademark "Masuo Details" for customizing Gunpla kits. He breaks down his process step-by-step across key areas – detailing up, paint arrangements, proportion modification, and more.`,
  },
  {
    slug: 'gundamfoward12',
    series: 'GUNDAM FORWARD',
    title: 'Mobile Suit Gundam: the Witch from Mercury – Alea jacta est',
    subtitle: 'Special 2! Spotlighting the intense duel battle scenes!',
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_86cda1b89dcf4caaba93d4962e665651~mv2.jpg/v1/fill/w_305,h_432,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B0CRYRZ4H3/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_854323c055554757b29433ca2faf716c.pdf',
    description: `In this special edition, we dive deep into the mobile suit designs featured in Mobile Suit Gundam: the Witch from Mercury. We've got exclusive interviews with the mechanical design team who share their creative process and inspiration behind crafting these unique mechas.`,
  },
  {
    slug: 'hjmechanics16',
    series: 'HJ MECHANICS',
    title: "Zeon's Awesome War Machines",
    subtitle: 'Covers a variety of military mechs from the Principality of Zeon!',
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_a55dbd67ca9b452eb166822d2b267748~mv2.jpg/v1/fill/w_307,h_392,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B0CP97TLT6/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_0d8a2deffb8a46288cf57f0c473ea95d.pdf',
    description: `The mechs of the Zeon military continue to captivate veteran Gundam fans. This book showcases the mobile suits that supported the Zeon military during the One Year War, using custom models created by professionals.`,
  },
  {
    slug: 'g-witch-gunpla-beginners-guide2',
    series: "BEGINNER'S GUIDE",
    title: "Mobile Suit Gundam: the Witch from Mercury Gunpla Beginner's Guide 2",
    subtitle: 'Enhance your Gunpla experience with this book!',
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_308a0f9048a4489089bcb3ac3871f3aa~mv2.jpg/v1/fill/w_305,h_431,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B0CKLFGHNG/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_259b61363b7a49cdbe3666972c38211e.pdf',
    description: `The eagerly awaited sequel to the G-Witch Gunpla Guide has arrived! This all-encompassing guide compiles instructions for various G-Witch Gunpla in the 1/144 scale and the sought-after 1/100 FULL MECHANICS version of the Gundam Aerial.`,
  },
  {
    slug: 'gf-gundam-seed',
    series: 'GUNDAM FORWARD',
    title: 'Mobile Suit Gundam SEED',
    subtitle: "An in-depth exploration of this beloved series, now with an upcoming movie adaptation!",
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_e15617d9aace4453adaabb4e7d3b0d9d~mv2.jpg/v1/fill/w_305,h_431,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B0CHMKKDDT/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_5b338371e449442792f827ba216846d6.pdf',
    description: `This edition of Gundam Forward focuses on Mobile Suit Gundam SEED, with its movie set to hit theaters this year. We'll provide an in-depth overview of the 2022 TV series and guide you through various building techniques from professional modelers.`,
  },
  {
    slug: 'gwitch-gunpla-beginnersguide',
    series: "BEGINNER'S GUIDE",
    title: "Mobile Suit Gundam: the Witch from Mercury Gunpla Beginner's Guide",
    subtitle: "With this book in hand, let's build the Gunpla of The Witch from Mercury!",
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_26d1dc676b8e4998af9a7b9b53b59d88~mv2.jpg/v1/fill/w_305,h_434,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B0CF59N13X/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_678cad7ec56d4190964b2d6667ecbcb1.pdf',
    description: `This guide will take you through the basic techniques required to build plastic models using the kits from the hugely popular Mobile Suit Gundam: The Witch from Mercury. These tips are effective and easy-to-learn, even for those who are just starting out with Gunpla.`,
  },
  {
    slug: 'gf-victory-gundam',
    series: 'GUNDAM FORWARD',
    title: 'Mobile Suit Victory Gundam',
    subtitle: '30th Anniversary of Mobile Suit Victory Gundam!',
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_0c39256e73c5481f9a8196bc392b54d2~mv2.jpg/v1/fill/w_305,h_434,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B0CBBLSGB2/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_86c7375870e2420e9d2b54665b93e355.pdf',
    description: `In this issue of Gundam Forward, we celebrate the 30th anniversary of Mobile Suit Victory Gundam, the final series in the Universal Century timeline to be adapted for animation.`,
  },
  {
    slug: 'gweapons-gudam-narrative',
    series: 'GUNDAM WEAPONS',
    title: 'Mobile Suit Gundam Narrative Special Edition',
    subtitle: 'GUNDAM WEAPONS, a leading series in the Gunpla boom, is finally releasing its English edition!',
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_709e5982bcd348369efd32f3d35c8117~mv2.jpg/v1/fill/w_305,h_431,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B0C7C6LCL6/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_fcc869c111894405b0d104b6792ffe2e.pdf',
    description: `GUNDAM WEAPONS began publication in 1989 and is one of the longest-running series of books on Gunpla. This book is the first English edition of the series and features a special focus on "Mobile Suit Gundam Narrative".`,
  },
  {
    slug: 'gundamfoward-g-witch',
    series: 'GUNDAM FORWARD',
    title: 'Mobile Suit Gundam: the Witch from Mercury',
    subtitle: "Step into the world of the latest Gundam TV series, the Witch from Mercury!",
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_c88651288a014b30ac7b5b93be03ac67~mv2.jpg/v1/fill/w_305,h_431,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B0BWJJLC6F/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_3b5b26c713e247719eca14c011d9f313.pdf',
    description: `This issue highlights the Witch from Mercury, the latest Gundam TV series, and its appeal through commentaries, Gunpla introductions, and how-to articles on Gunpla construction.`,
  },
  {
    slug: 'charscounterattack',
    series: 'HJ MECHANICS',
    title: "Mobile Suit Gundam: Char's Counterattack",
    subtitle: "Looking back at Char's Counterattack!, a timeless masterpiece!",
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_b8a37255cdca4b9a8d3ff3fceba461ee~mv2.jpg/v1/fill/w_309,h_392,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B0BSV4RHKQ/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_a1078113d7d84ffa837c52f95abcd64c.pdf',
    description: `Let's look back at the era of Char's rebellion and explore the history of mobile suit design. Check out the memorable scenes from the movie, recreated with custom kits and dioramas from professional modelers.`,
  },
  {
    slug: 'gundam-forward-vol-6',
    series: 'GUNDAM FORWARD',
    title: 'New Mobile Report Gundam Wing: Endless Waltz Vol.2',
    subtitle: 'More about the Gundam Wing: Endless Waltz!',
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_ff91d11c20144d10b07bd0e64a49dde5~mv2.jpg/v1/fill/w_305,h_431,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/gp/product/B0BNL9N3J4/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_cc405c075bce4f5eb21e4928bca1bcd7.pdf',
    description: `New Mobile Report Gundam Wing: Endless Waltz, which was well received in the previous issue, is featured again in this issue. While the last issue focused on the custom kits of the main characters' first five Gundams, we will now shift our attention to the mobile suits in the latter half of the story.`,
  },
  {
    slug: 'gundamforward4',
    series: 'GUNDAM FORWARD',
    title: 'New Mobile Report Gundam Wing: Endless Waltz',
    subtitle: 'Immerse yourself in the world of Gundam Wing!',
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_0abd0acb1aac4a31938f7713794e1cb8~mv2.jpg/v1/fill/w_305,h_431,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B0BK9Y44CB/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_1bd44627f56a40a6889b4941f43e381b.pdf',
    description: `This issue includes New Mobile Report Gundam Wing: Endless Waltz, an OVA from the Mobile Suit Gundam Wing series. To commemorate the release of the latest kit, MG Wing Gundam Zero EW Ver. Ka, we built all five character's Gundam units (early types) to show you!`,
  },
  {
    slug: '10-essential-gunpla-techniques',
    series: 'TECHNIQUE GUIDE',
    title: 'Ten Essential Techniques to Achieve Absolute Mastery of Gunpla',
    subtitle: 'A 10-step easy-to-follow guide using the "ENTRY GRADE 1/144 RX-78-2 Gundam"!',
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_411073eda97943e8af59535e34aaeee0~mv2.png/v1/fill/w_305,h_431,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.png',
    amazonUrl: 'https://www.amazon.com/dp/B09VGQVLV2/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_9039592552f742aeb448bd0a8e3b56e1.pdf',
    description: `This book guides you through practical Gunpla construction techniques in a ten-step how-to format using the "ENTRY GRADE 1/144 RX-78-2 Gundam," the first Gunpla of the next generation, which is easy for anyone to assemble.`,
  },
  {
    slug: 'gunpla-super-technique-teppei',
    series: 'TECHNIQUE GUIDE',
    title: 'Gunpla Super Technique – Technical Guide for Awesome Mobile Suits Modeling (Teppei Hayashi)',
    subtitle: 'Creating "the Ultimate Custom Model" without restrictions.',
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_4f905bfef173493faa27813892d9cf05~mv2.jpg/v1/fill/w_305,h_431,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B0B79FV513/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_ce6eeb133eba4ebaa5ef6a46015e0b4b.pdf',
    description: `Teppei Hayashi compiled all the articles from his popular magazine corner, "Teppei Hayashi's Technical Guide for Awesome Mobile Suits Modeling" in HJ Mechanics, into one book!`,
  },
  {
    slug: 'hg-gunpla-super-technique-easy-f',
    series: 'TECHNIQUE GUIDE',
    title: 'Gunpla Super Technique – HG Models Easy Finishes',
    subtitle: 'Creating "the Ultimate Custom Model" without restrictions.',
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_69f144d121f244859b64bb4a7355f41d~mv2.jpg/v1/fill/w_305,h_431,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B09DPK6YGD/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_bfaca87e52fe4bdba44d5d23dcb46a56.pdf',
    description: `This volume focuses on HG models, which are cheaper and easier to test your skills on. This book offers various techniques, from standard modeling to famous professional modelers' crafting techniques with new articles.`,
  },
  {
    slug: 'gunpla-easy-custom-guide',
    series: 'TECHNIQUE GUIDE',
    title: 'Gunpla Easy Custom Guide for Beginners to Intermediate',
    subtitle: 'Get professional results on a budget, faster!',
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_6fed18fdbb6f439293cd6b6c87fb2194~mv2.jpg/v1/fill/w_305,h_431,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B09C1YB539/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_520f643121254ed49370a9e9d11750d9.pdf',
    description: `This book explains the Gunpla building techniques promoted by Rider Joe, a modeler active in Monthly Hobby Japan. His comprehensive methods offer cost-effective approaches that do not use expensive tools and will save you time.`,
  },
  {
    slug: 'nomoken3',
    series: 'TECHNIQUE GUIDE',
    title: 'NOMOKEN 3: Complete Guide to Gunpla Building',
    subtitle: 'The long-awaited sequel to Nomoken extra edition!',
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_aba3bd3677124856a767786417729135~mv2.png/v1/fill/w_323,h_392,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.png',
    amazonUrl: 'https://www.amazon.com/dp/B09923RQ4K/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_9f584441301c462492ce106476a0a15f.pdf',
    description: `A perfect manual for Gunpla modelers who want to reach the next level! Whether you're just aiming for a straight build or you want to turn a Gunpla into your own piece of art, this book is for you.`,
  },
  {
    slug: 'ibo-original',
    series: 'GUNDAM FORWARD',
    title: 'Mobile Suit Gundam: Iron-Blooded Orphans',
    subtitle: 'Gundam Forward: "Relaying the forefront of Gundam"',
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_5087292a4cd244d68dc87d98ee24e97e~mv2.jpg/v1/fill/w_305,h_430,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B08ZN5YBC9/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_290bcaefff3a448f8acf0a38fb9ebb95.pdf',
    description: `Over than five years after the first broadcast of the series, Mobile Suit Gundam: IRON-BLOODED Orphans doesn't stop growing! We will look back on the past while thoroughly reviewing and assembling the latest Gunpla.`,
  },
  {
    slug: 'hjmechanics-history-of-gupla',
    series: 'HJ MECHANICS',
    title: 'HJ Mechanics – History of Gunpla Techniques',
    subtitle: 'HJ Mechanics: a hobby magazine for mech lovers!',
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_600c85b6d2de46de84fe1ae9b0d6cf33~mv2.jpg/v1/fill/w_305,h_392,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B08WXCRMV2/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_7446cda8e7194b0a85a3e764ab17ecb6.pdf',
    description: `This book delves deep into mechs, focusing on models and toys for an older audience. The charm of robots and other mechs is explored from various angles with custom builds by skilled modelers.`,
  },
  {
    slug: 'gunpla-super-technique01',
    series: 'TECHNIQUE GUIDE',
    title: 'Gunpla Super Technique – Easy Finishes for Weekend Modelers',
    subtitle: 'The ultimate guide to building cool Gunpla over the weekend!',
    coverUrl: 'https://static.wixstatic.com/media/37bf6a_e4575ca49004438288d8b7506225c5c9~mv2.jpg/v1/fill/w_305,h_431,al_c,q_80,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.jpg',
    amazonUrl: 'https://www.amazon.com/dp/B08Q7TZXVD/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_0ad94d0f10124361a60c88eeb1de7fb0.pdf',
    description: `The popular tutorial series on easy finishes published in Monthly Hobby Japan has been turned into a book, together with new how-tos and custom models! Detailed step-by-step guides will teach you easy techniques to finish your model.`,
  },
  {
    slug: 'nomoken-extra',
    series: 'TECHNIQUE GUIDE',
    title: 'NOMOKEN Extra Edition – Handbook of Gunpla Modeling',
    subtitle: 'The first official English Gunpla modeling manual!',
    coverUrl: 'https://static.wixstatic.com/media/fa5755_3e8ea1943fa8483892b54c5db36646af~mv2.png/v1/fill/w_320,h_392,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/HJ_Mechanics04_cover.png',
    amazonUrl: 'https://www.amazon.com/dp/B08LDB1ZTH/',
    pdfUrl: 'https://www.english.hobbyjapan.co.jp/_files/ugd/37bf6a_064313ad36764bdf8b820e841c4c3e1c.pdf',
    description: `This book covers the full process of building Gunpla, from the very basics to more advanced techniques to make your model look cooler. Whether you are a beginner about to build your first kit or you are looking to take your technique one step further, you will find plenty of useful tips and step-by-step tutorials to suit your needs.`,
  },
]

async function migrate() {
  console.log(`Migrating ${books.length} books to Sanity...`)

  const transaction = client.transaction()

  books.forEach((book, i) => {
    const doc = {
      _id: `book-${book.slug}`,
      _type: 'book',
      slug: { _type: 'slug', current: book.slug },
      series: book.series,
      title: book.title,
      subtitle: book.subtitle,
      isNew: book.isNew ?? false,
      releaseDate: book.releaseDate,
      coverUrl: book.coverUrl,
      amazonUrl: book.amazonUrl,
      pdfUrl: book.pdfUrl,
      description: book.description,
      order: i,
    }
    transaction.createOrReplace(doc)
  })

  await transaction.commit()
  console.log(`✅  Done! ${books.length} books imported.`)
}

migrate().catch((err) => {
  console.error('Migration failed:', err.message)
  process.exit(1)
})
